name: Build and Test
on:
  push: {}
  workflow_dispatch: {}

env:
  MAJOR_MINOR: '0.0'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        id: version
        run: echo "::set-output name=version::${MAJOR_MINOR}.${GITHUB_RUN_NUMBER}"

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'

      - name: Run tests
        run: go test ./...

      - name: Build
        run: ./build.sh ${MAJOR_MINOR}.${GITHUB_RUN_NUMBER}

      - name: Tag
        uses: rickstaa/action-create-tag@v.1.3.2
        with:
          tag: v${{ steps.version.outputs.version }}
          message: 'Version: ${{ steps.version.outputs.version }}'

      - name: Release
        if: contains(github.ref, 'main')
        run: ./release.sh ${{ steps.version.outputs.version }} ${{ secrets.SPECGEN_GITHUB_TOKEN }} ${{ secrets.JFROG_USER }} ${{ secrets.JFROG_PASS }}